apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: sosialhjelp-fss-proxy
  namespace: teamdigisos
  labels:
    team: teamdigisos
spec:
  receivers:
    slack:
      channel: digisos-alerts-dev
      prependText: "<!here> | "
  alerts:
  - alert: sosialhjelp-fss-proxy er nede
    description: "App {{ $labels.app }} er nede i namespace {{ $labels.kubernetes_namespace }}"
    expr: kube_deployment_status_replicas_available{deployment="sosialhjelp-fss-proxy" } == 0
    for: 2m
    action: "kubectl describe pod {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for logger"
    documentation: "https://github.com/navikt/teamdigisos/somedoc"
    sla: "Responder innen 1 time i kontortid"
    severity: danger
  - alert: Mye feil i loggene
    expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="sosialhjelp-fss-proxy",log_level=~"Error"}[3m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="sosialhjelp-fss-proxy" }[3m]))) > 10
    for: 3m
    action: "Sjekk loggene til app {{ $labels.log_app }} i namespace {{ $labels.log_namespace }} for å se hvorfor det er så mye feil"
    sla: "Responder innen 1 time i kontortid"
    severity: warning