apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sosialhjelp-fss-proxy
  namespace: teamdigisos
  labels:
    team: teamdigisos
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: "/internal/isAlive"
    port: 8080
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/internal/isReady"
    port: 8080
    initialDelay: 20
    timeout: 60
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: "/internal/prometheus"
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 1m
      memory: 256Mi
  ingresses:
  {{#each ingress}}
     - "{{this}}"
  {{/each}}
  tokenx:
    enabled: {{tokenXEnabled}}
  accessPolicy:
    inbound:
      rules:
      {{#each inboundRulesGcpApplications}}
        - application: "{{this}}"
          cluster: {{gcpCluster}}
      {{else}}
        []
      {{/each}}
      {{#if hasInboundSbsApps}}
      {{#each inboundRulesSbsApplications}}
        - application: "{{this}}"
          cluster: {{sbsCluster}}
      {{/each}}
      {{/if}}
  env:
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
