spring:
  main:
    banner-mode: off

fss-proxy:
  tokendings_client_id: ${TOKEN_X_CLIENT_ID}
  tokendings_url: ${TOKEN_X_WELL_KNOWN_URL}
  tokendings_private_jwk: ${TOKEN_X_PRIVATE_JWK}
  krr_url: ${KRR_URL}
  krr_audience: ${KRR_AUDIENCE}
  aareg_url: ${AAREG_URL}
  aareg_audience: ${AAREG_AUDIENCE}

# Prometheus
management:
  endpoints:
    web:
      base-path: "/internal"
      exposure:
        include: info, health, metrics, prometheus
