name: Deploy til dev-fss
on:
  workflow_dispatch:

jobs:
  deployAppToDev:
    name: Deploy to dev-fss
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
      - name: Deploy app to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: .nais/nais.yaml
          CLUSTER: dev-fss
          VARS: .nais/dev-fss.json
          REF: ${{ github.sha }}
          PRINT_PAYLOAD: true
          IMAGE: ${{ env.IMAGE }}
  deployAlertsToDev:
    name: Deploy alerts to dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy alerts to DEV
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: .nais/alerts-dev.yaml
          VARS: .nais/dev-fss.json