name: Deploy til dev-fss
on:
  workflow_dispatch:

jobs:
  deployAppToDev:
    name: Deploy to dev-fss
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy app to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: .nais/nais-dev.yaml
          CLUSTER: dev-fss
          REF: ${{ github.sha }}
          PRINT_PAYLOAD: true
          IMAGE: ${{ env.IMAGE }}
